# Docker configuration for Trinetra
base_path: "/app/data/stl_files"
gcode_path: "/app/data/gcode_files"
# Set this to your actual Moonraker URL (e.g., "http://192.168.1.100:7125")
moonraker_url: ""
log_level: "INFO"
mode: "PROD"
search_result_limit: 100